### ISSUE TITLE
generate wifi QRCode

### ISSUE THREAD

**Issue by karlTH** [ricmoo/QRCode#2]
Hello,

Did you thinks that it's possible to generate qrCode for wifi access ?

Thanks a lot for the librarie.

**Comment by ricmoo** [comment]
Yupp, you certainly can. :)

Here is the [long version](https://github.com/zxing/zxing/wiki/Barcode-Contents#wifi-network-config-android) from zebra crossing, but the TL;DR for your purposes can just use this format:

WIFI:S:<ssid>;T:<WPA|WEP|>;P:<password>;;

For example:

WIFI:S:STARBUCKS;T:WPA;P:PASSWORD123;;

Hope that helps.

**Comment by karlTH** [comment]
thanks a lot
