### ISSUE TITLE
Cannot scan qrcodes for version 2 and 3 with android qrdroid reader

### ISSUE THREAD

**Issue by brennino** [ricmoo/QRCode#25]
Hello,
I want to report that I'm having issues with qr codes version 2 and 3.
I tried to scan qr code generated with this versions and qr droid for android is not able to detect them. I tried to generate qrcodes version 4 and 5 and I can scan them without any issue.
This sound strange, maybe a qr droid issue but I want to report the problem anyway to better investigate and check if other people noticed the same thing.
Thanks for this software,
Regards

**Comment by ricmoo** [comment]
Can you include the data you are putting in the QR code? Could it be too much data for the QR code version and ECC type?

**Comment by brennino** [comment]
Hello, thanks for your fast reply.
I'm trying to solve this issue on my own for days without any result and now that I have decided to open here an issue I found what's wrong; my fault sorry.
But maybe this can help other people.
As "Alphanumeric" characters in the table, it seems is intended this kind of characters:
 - 0 to 9, A to Z (uppercase only), space, dollar, percent, asterisk, plus, hyphen, period, slash, colon.

When other signs exists inside the string (for example an equal and question mark characters in my case), you have to check the byte size in the column showed in documentation.
In my case I give a string length that is ok for alphanumeric section, too long for byte section but contains characters that are not "alphanumeric" resulting in a wrong qrcode generation.

Really appreciate your work and hope that this can help other people that are trying to generate some beautiful qr codes like me.

Best Regards,

Marco

UPDATE: I checked again your docs, it's clearly stated! Next time I read it 5 times more :) sorry.

**Comment by ricmoo** [comment]
No worries. It happens. :)
